name: 'CTS Install'
description: 'Downloads and installs a specific version of CTS'
inputs:
  miliseconds:  # id of input
    description: 'The miliseconds to wait'
    required: true
    default: '1000'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  pre: 'build.js'
  main: 'dist/index.js'
  